config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "welcome#index"
  resources :stores do 
    resources :items
    member do
        get :admin_panel
    end    
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :store
  has_many :item_transactions
  has_many :transactions, :through => :item_transactions
end

app/models/item_transaction.rb
class ItemTransaction < ApplicationRecord
  belongs_to :item
  belongs_to :user

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :items, :through => :order_items
  belong_to :user
  
end

app/models/order_items.rb
class OrderItems < ApplicationRecord
  belongs_to :item
  belongs_to :user

end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :items
  has_many :orders, :through => :items

  scope  :store_items, -> {Item.where(:store_id => Store.last)}
  #items = Item.all
  #stores = Store.joins(:item).where('item.id IN (?)', items.store_id)

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :stores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	  helper_method :current_order

	  def current_order
	    if session[:order_id]
	      Order.find(session[:order_id])
	    else
	      Order.new
	    end
	  end
end

app/controllers/item_controller.rb
class StoreController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end 

  def update
    @item.update(item_params)
  end

  def create
    @item = Item.new()
    @item.save
  end

  def destroy
    @item.destroy
  end


  private

  def find_item
    @item = Item.find(params[:id])
  end

  def store_params
    params.require(:item).permit(:item_name, :item_price)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end 

  def update
    @item.update(item_params)
  end

  def create
    @store = Store.find(params[:store_id])
    @item = Item.new(item_params)
    @item.store_id = @store.id
    @item.save!
    redirect_to "/stores"
  end

  def destroy
    find_item
    @item.destroy
  end


  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:item_name, :item_price, :description, :photo)
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  before_action :authenticate_user!

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def edit
    @store = Store.find(params[:id])
  end 

  def update
    @store.update(store_params)
  end

  def create
    @store = Store.new()
    @store.save
  end

  def destroy
    @store.destroy
  end


  private

  def find_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:store_name)
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!

  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end

  def new
    @store = Store.new
  end

  def edit
    @store = Store.find(params[:id])
  end 

  def update
    find_store
    @store.update(store_params)
  end

  def create
    @store = Store.new(store_params)
    @store.user_id = current_user.id
    @store.save!
  end

  def destroy
    find_store
    @store.destroy
  end

  def admin_panel
    @store = Store.find(params[:id])
  end


  private

  def find_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:store_name, :slogan, :description, :photo)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_new_item_form.html.erb
<%= form_for @item, url: store_items_path, :html => {:class => "form-horizontal center"} do 
    |f| %>
    <div class="form-group">
      <%= f.label :item_name, "Item name", class: "col-md-4 control label" %>
      <div class="col-md-4">
        <%= f.text_field :item_name, class: "form-control",
        placeholder: "Product name" %>
      </div>
      <div class="form-group">
        <%= f.label :item_price, "Price", class: "col-md-4 control-label" %>
      </div>
      <div class="col-4">
        <%= f.text_field :item_price, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "Describe your store", class: "col-md-4 control-label" %>
      </div>
      <div class="col-4">
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :photo, "Add your photo", class: "col-md-4 control-label" %>
      </div>
      <div class="col-4">
        <%= f.text_field :photo, class: "form-control" %>
      </div>

    </div>

    <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
 <% end %>

app/views/items/edit.html.erb
<%= render "new_item_form" %>

app/views/items/index.html.erb
<style type="text/css">
  img {
    width: 100px;
  }
</style>



<div class="container no-gutter">

  <% @items.each do |item| %>
  
    <li>
        <a href="items/<%=item.id%>">
      <div class="col-sm-3">
        <div class="row">
          <div><img src="<%= item.photo %>"></div>
          <div><h5><%= item.item_name %></h5></div>
          <div><h6><%= item.description %></h6></div>
          <br>
          <div class="type"><%= item.item_price %></div>
        </a>
    
           <% end %>
        </div>
     </div>
    </li>
</div>


<div><%= link_to 'New',  "/stores/", method: :get, class: 'btn btn-primary' %><div>

app/views/items/items_summary.html.erb
<style type="text/css">
  img {
    width: 100px;
  }
</style>



<div class="container no-gutter">

  <% @items.each do |item| %>
  
    <li>
      
      <div class="col-sm-3">
        <div class="row">
          <div><img src="<%= item.photo %>"></div>
          <div><h5><%= item.item_name %></h5></div>
          <div><h6><%= item.description %></h6></div>
          <br>
          <div class="type"><%= item.item_price %></div>
        </a>
    
           <% end %>
        </div>
     </div>
    </li>
</div>
<div><%= link_to 'New',  "/stores/new", method: :get, class: 'btn btn-primary' %><div>

app/views/items/new.html.erb
<%= render "new_item_form" %>

app/views/items/show.html.erb
<div><%= @item.item_name %></div>
<div><%= @item.description %></div>
<div style="width: 500px"><img class="card-img-top" src="<%= @item.photo %>" alt=""></div>

<div><%= link_to 'Back',  store_path, method: :get, class: 'btn btn-primary' %><div>
</div>


<div><%= link_to 'Remove Item',  store_item_path, method: :delete, class: 'btn btn-danger' %><div>
 <div><%= link_to 'Edit',  edit_store_item_path, method: :get, class: 'btn btn-primary' %><div>

app/views/layouts/_navbar_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Storator</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/books/#list-of-books">Catalog <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">News</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
          <p class="dropdown-item">Logged as:  <%= current_user.email %></p>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'dropdown-item' %> |
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item'  %>
          </div>
          <% else %>
            <%= link_to 'Register', new_user_registration_path, {:class => 'dropdown-item btn btn-small btn-success'}  %> |
            <%= link_to "Login", new_user_session_path, {:class => 'dropdown-item btn btn-small'}  %>
          <% end %>

      </li>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Storator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <ul class="nav">
      <li class="active"><a href="/ideas">Storator</a></li>
    </ul>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/stores/_new_store_form.html.erb
<%= form_for @store, :html => {:class => "form-horizontal center"} do 
    |f| %>
    <div class="form-group">
      <%= f.label :store_name, "Name of your store:", class: "col-md-4 control label" %>
      <div class="col-md-4">
        <%= f.text_field :store_name, class: "form-control",
        placeholder: "Store name" %>
      </div>
      <div class="form-group">
        <%= f.label :slogan, "Add your Slogan", class: "col-md-4 control-label" %>
      </div>
      <div class="col-4">
        <%= f.text_field :slogan, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "Describe your store", class: "col-md-4 control-label" %>
      </div>
      <div class="col-4">
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :photo, "Add your photo", class: "col-md-4 control-label" %>
      </div>
      <div class="col-4">
        <%= f.text_field :photo, class: "form-control" %>
      </div>
    
    </div>

    <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
 <% end %>

app/views/stores/_new_store_template.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Frontpage - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/business-frontpage.css" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header with Background Image -->
    <header class="business-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1 class="display-3 text-center text-white mt-4">Business Name or Tagline</h1>
          </div>
        </div>
      </div>
    </header>

    <!-- Page Content -->
    <div class="container">

      <div class="row">
        <div class="col-sm-8">
          <h2 class="mt-4">What We Do</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum.</p>
          <p>
            <a class="btn btn-primary btn-lg" href="#">Call to Action &raquo;</a>
          </p>
        </div>
        <div class="col-sm-4">
          <h2 class="mt-4">Contact Us</h2>
          <address>
            <strong>Start Bootstrap</strong>
            <br>3481 Melrose Place
            <br>Beverly Hills, CA 90210
            <br>
          </address>
          <address>
            <abbr title="Phone">P:</abbr>
            (123) 456-7890
            <br>
            <abbr title="Email">E:</abbr>
            <a href="mailto:#">name@example.com</a>
          </address>
        </div>
      </div>
      <!-- /.row -->

      <div class="row">
        <div class="col-sm-4 my-4">
          <div class="card">
            <img class="card-img-top" src="http://placehold.it/300x200" alt="">
            <div class="card-body">
              <h4 class="card-title">Card title</h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus.</p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">Find Out More!</a>
            </div>
          </div>
        </div>
        <div class="col-sm-4 my-4">
          <div class="card">
            <img class="card-img-top" src="http://placehold.it/300x200" alt="">
            <div class="card-body">
              <h4 class="card-title">Card title</h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut.</p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">Find Out More!</a>
            </div>
          </div>
        </div>
        <div class="col-sm-4 my-4">
          <div class="card">
            <img class="card-img-top" src="http://placehold.it/300x200" alt="">
            <div class="card-body">
              <h4 class="card-title">Card title</h4>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque.</p>
            </div>
            <div class="card-footer">
              <a href="#" class="btn btn-primary">Find Out More!</a>
            </div>
          </div>
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/stores/admin_panel.html.erb
<h1>ADMIN PANEL</h1>
<h3>Welcome <%= current_user.name %></h3>

<div>
    <p>View your store</p>
    <div><%= link_to 'View store',  "/stores/#{@store.id}", method: :get, class: 'btn btn-primary' %><div>
    <p>Edit your store</p>
    <div><%= link_to 'Edit your store',  "/stores/#{@store.id}/edit", method: :get, class: 'btn btn-primary' %><div>
    <p>Manage your items</p>
    <div><%= link_to 'Manage Items',  store_items_path(@store.id), method: :get, class: 'btn btn-primary' %><div>

    <p>Add items to your store</p>
    
    <div><%= link_to 'Add a new Item',  new_store_item_path(@store.id), method: :get, class: 'btn btn-primary' %><div>
    <p>Delete your store</p>
    <div><%= link_to 'Delete your store',  "/stores/#{@store.id}", method: :delete, class: 'btn btn-danger' %><div>

</div>

<div><%= link_to 'Back',  "/stores/", method: :get, class: 'btn btn-primary' %><div>
</div>

app/views/stores/edit.html.erb
<%= render "new_store_form" %>

app/views/stores/index.html.erb
<style type="text/css">
  img {
    width: 100px;
  }
</style>



<div class="container no-gutter">

  <% @stores.each do |store| %>
  
    <li>
      <a href="/stores/<%= store.id%>/admin_panel">
      <div class="col-sm-3">
        <div class="row">
          <div><img src="<%= store.photo %>"></div>
          <div><h5><%= store.store_name %></h5></div>
          <div><h6><%= store.slogan %></h6></div>
          <br>
          <div class="type"><%= store.store_name %></div>
        </a>
    
           <% end %>
        </div>
     </div>
    </li>
</div>
<div><%= link_to 'New',  "/stores/new", method: :get, class: 'btn btn-primary' %><div>

app/views/stores/new.html.erb
<%= render "new_store_form" %>

app/views/stores/show.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>


    <title><%= @store.store_name %></title>
    <style type="text/css">
      
    img{
      width: 100vh;
    }

    </style>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#"><%= @store.store_name %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header with Background Image -->
    <header class="business-header" > <img src="<%=@store.photo%>">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h3 class="display-3 text-center text-black mt-4"><%= @store.slogan%></h1>
          </div>
        </div>
      </div>
    </header>

    <!-- Page Content -->
    <div class="container">

      <div class="row">
        <div class="col-sm-8">
          <h2 class="mt-4">What We Do</h2>
          <p><%= @store.description %></p>
          <p>
            <a class="btn btn-primary btn-lg" href="#">Call to Action &raquo;</a>
          </p>
        </div>
        <div class="col-sm-4">
          <h2 class="mt-4">Contact Us</h2>
          <address>
            <strong>Start Bootstrap</strong>
            <br>3481 Melrose Place
            <br>Beverly Hills, CA 90210
            <br>
          </address>
          <address>
            <abbr title="Phone">P:</abbr>
            (123) 456-7890
            <br>
            <abbr title="Email">E:</abbr>
            <a href="mailto:#">name@example.com</a>
          </address>
        </div>
      </div>
      <!-- /.row -->


      <div class="container no-gutter">

        <% @store.items.each do |item| %>
      


      <div class="row">
        <div class="col-sm-4 my-4">
          <div class="card">
            <img class="card-img-top" src="<%= item.photo %>" alt="">
            <div class="card-body">
              <h4 class="card-title"><%= item.item_name %></h4>
              <p class="card-text"><%= item.description %></p>
              <p class="card-text">$<%= item.item_price %></p>
            </div>
            <div class="card-footer">
              
              <%= link_to 'Details',  store_item_path(:store_id), method: :get, class: 'btn btn-primary' %>

            </div>
          </div>
        </div>
        

      </div>

      <% end %>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/welcome/index.html.erb
<!-- <%= react_component 'GreetUser', name: 'Lili' %> -->
<style type="text/css">

  .masthead {

    background-color: black;
   /* background-image: url("https://images.pexels.com/photos/103567/pexels-photo-103567.jpeg?auto=compress&cs=tinysrgb&h=650&w=940"); */
    background-size: cover;
    height: 50vh;
    color: blue;
    background-repeat: no-repeat;
    overflow-y: hidden;

}

.button {
    background-color: #745cf9; /* Blue */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
}

/* Gallery */

div.gallery {
    margin: 5px;
    border: 1px solid #ccc;
    float: left;
    width: 180px;
}

div.gallery:hover {
    border: 1px solid #777;
}

div.gallery img {
    width: 100%;
    height: auto;
}

div.desc {
    padding: 15px;
    text
  }

.carousel-inner img {
      width: 100%;
      height: 100%;
  }

footer {
  background-color: black;
}





</style>


<header class="masthead">
   <div class="container">
       <hr class="star-light">

  <div><%= link_to 'New Store',  "/stores", method: :get, class: 'button1' %><div>
  <button class="button button1">Learn more</button>
  </div>
</header>


<nav><%= render "layouts/navbar_header" %></nav>
<section class="section1">
  <div class="container">
    <div class="row">
      <div class="col-6"> 
        <div>
          <img src="https://images.pexels.com/photos/331990/pexels-photo-331990.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" width="300px">
        </div>   
      </div>
      <div class="col-6">
        <h2>Create your own brand in your own way</h2>
        <h6>You dont need any technical knowledge</h6>
        <p>Establece tu marca en línea con un dominio personalizado y una tienda online. Recibe acceso instantáneo a cientos de las más hermosas plantillas, y controla completamente el look y la imagen de tu marca. Finalmente podrás crear una tienda online propia que refleja tu personalidad y la de tu negocio.</p>
      </div>
    </div>
  </div>
</section>

<section>
  <h3>Sucess Stories</h3>
  <div class="gallery">
    <a target="_blank" href="img_5terre.jpg">
      <img src="https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="5Terre" width="600" height="400">
    </a>
    <div class="desc">Add a description of the image here</div>
  </div>

  <div class="gallery">
    <a target="_blank" href="img_forest.jpg">
      <img src="https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="Forest" width="600" height="400">
    </a>
    <div class="desc">Add a description of the image here</div>
  </div>

  <div class="gallery">
    <a target="_blank" href="img_lights.jpg">
      <img src="https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="Northern Lights" width="600" height="400">
    </a>
    <div class="desc">Add a description of the image here</div>
  </div>

</section>



<section class="best_stores">
  <div id="demo" class="carousel slide" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://images.pexels.com/photos/450059/pexels-photo-450059.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="Los Angeles" width="500" height="500">
        <div class="carousel-caption">
          <h3>Los Angeles</h3>
          <p>We had such a great time in LA!</p>
        </div>   
      </div>
      <div class="carousel-item">
        <img src="https://images.pexels.com/photos/212286/pexels-photo-212286.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="Chicago" width="500" height="500">
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago!</p>
        </div>   
      </div>
      <div class="carousel-item">
        <img src="https://images.pexels.com/photos/904276/pexels-photo-904276.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" alt="New York" width="500" height="500">
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>We love the Big Apple!</p>
        </div>   
      </div>
    </div>
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
</section>

<footer>
  
</footer>